### ISSUE TITLE
Test polarToCartesian(...) and cartesianToPolar(...) functions in BB.MathUtils.

### ISSUE THREAD

**Issue by brannondorsey** [brangerbriz/liBB.js#13]
These functions appear to be correct as [Processing explains](https://processing.org/examples/polartocartesian.html) and uses them however they do not provide the expected results from online polar-to-cartesian conversion resources like [this](http://www.engineeringtoolbox.com/converting-cartesian-polar-coordinates-d_1347.html).

**Comment by nbriz** [comment]
i rewrote these two functions ( for what is now BB.Maths ) like so:
```javascript
static cartesianToPolar(x, y) 
// returns { distance, radians, degrees }

static polarToCartesian(distance, angle ) // angle in radians
// returns { x, y }

```
