### ISSUE TITLE
Examples Gallery Page

### ISSUE THREAD

**Issue by brannondorsey** [brangerbriz/liBB.js#18]
It would be nice to have a gallery page with thumbnails/gifs of each example (probably `examples/index.html`). These examples could be organized by type and clicking each one could be open the example in the editor with `editor.html?file=`. We should also begin to link to examples in our documentation.

**Comment by nbriz** [comment]
Yea and maybe iframe instead of gifs? Then the whole thing could be autogenerated

**Comment by brannondorsey** [comment]
I like that idea. The only problem with that is that some of the examples won't look good at all in an iframe (i'm thinking pointers, etc... which is basically an empty white page). Perhaps if there is a `thumbnail.*` file in the root of each example it uses that, otherwise it automatically creates an iframe? I haven't used iframes a ton, is there a way to scale the contents of the frame so that the width of the page being included is scaled proportionately to the width of the iframe (i.e. you experience the page that is included in the iframe as a very small full page)?

**Comment by brannondorsey** [comment]
Also, will we run into sluggish framerates if we run all of our examples in iframes on a single page?

**Comment by brannondorsey** [comment]
We've got a basic version of this working now.
